apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "productpage.fullname" . }}
  labels:
    app: {{ template "productpage.name" . }}
    canary: "false"
    chart: {{ template "productpage.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.productionDeployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "productpage.name" . }}
      canary: "false"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "productpage.name" . }}
        canary: "false"
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.productionDeployment.image.repository }}:{{ .Values.productionDeployment.image.tag }}"
          imagePullPolicy: {{ .Values.productionDeployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
