apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-page-virtual-service
  labels:
    chart: {{ template "productpage.chart" . }}
    release: {{ .Release.Name }}
spec:
  hosts:
  - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
  gateways:
  - product-page
  http:
  - route:
    - destination:
        host: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
        subset: production
        port:
          number: {{ .Values.service.port }}
      weight: {{ .Values.productionDeployment.weight }}
    - destination:
        host: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
        subset: canary
        port:
          number: {{ .Values.service.port }}
      weight: {{ .Values.canaryDeployment.weight }}